#!/usr/bin/env python3
# CONFIRMED-SECRET-OK: every literal below is synthetic placeholder data written
# into a throwaway temp directory. No real domain, key, file or PII appears.
"""
Regenerate ../sample-report.md by running the REAL scanner against a synthetic
home directory.

The sample report is NOT hand-written. If it were, it would drift from what the
tool actually prints, and a security tool whose own example output is stale is
exactly the kind of thing this repo exists to not be. Everything below builds a
fake $HOME, points Path.home() at it, runs the real run_scan() + the real
render_markdown(), and then normalises the two non-deterministic things (the
temp path and the generation timestamp) into stable placeholders.

    python3 tests/make-sample-report.py            # rewrite ../sample-report.md
    python3 tests/make-sample-report.py --check    # exit 1 if it would change

Fixture SSH keys are generated with ssh-keygen into the throwaway home and are
destroyed with it.
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import re
import shutil
import sqlite3
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import exposurescan as es  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "sample-report.md"

FIXED_EPOCH = 1_767_225_600          # 2026-01-01 00:00:00 UTC
CORE_DATA_MODIFIED = 788_918_400.0   # 2026-01-01 00:00 UTC in Core Data seconds

SEED_PHRASE = (
    "abandon ability able about above absent absorb abstract absurd abuse "
    "access accident"
)

BANNER = """<!--
  NOTE: every entry below is FAKE / PLACEHOLDER data, generated by running the
  REAL scanner against a synthetic home directory (tests/make-sample-report.py).
  It is regenerated from actual output rather than hand-written, so it cannot
  drift from what the tool does. No real domains, keys, files, or PII.

  The Apple Notes entry is the interesting one: that note's first line — and
  therefore its ZTITLE1 "title" — is the canonical public BIP-39 test mnemonic.
  The report tells you the note exists, that it is P0, how long the title is,
  and when it was last edited. It does not tell you a single word of it.

  The SSH rows are the second interesting pair: one key has a passphrase and one
  does not, and only the passphrase-less one is P0.
-->"""


def _touch(path: Path) -> None:
    os.utime(path, (FIXED_EPOCH, FIXED_EPOCH))


def build_home(home: Path) -> None:
    # --- (c) .env ---------------------------------------------------------
    proj = home / "dev" / "example-app"
    proj.mkdir(parents=True)
    env = proj / ".env"
    env.write_text(
        "EXAMPLE_PUBLIC_APP_NAME=example\n"
        "EXAMPLE_PUBLIC_URL=https://example.test\n"
        "EXAMPLE_DB_URL=postgres://user:PLACEHOLDERvalue@db.example.test:5432/app\n"
        "EXAMPLE_AWS_ACCESS_KEY_ID=AKIAPLACEHOLDER00000\n"
        "EXAMPLE_STRIPE_SECRET_KEY=PLACEHOLDER-entropy-0123456789abcdef\n"
    )
    os.chmod(env, 0o644)

    # --- (d) ~/.secrets ---------------------------------------------------
    secrets = home / ".secrets"
    secrets.mkdir(mode=0o700)
    (secrets / "example-api-key").write_text("PLACEHOLDER" * 5 + "\n")
    os.chmod(secrets / "example-api-key", 0o644)
    (secrets / "example-token").write_text("PLACEHOLDER\n")
    os.chmod(secrets / "example-token", 0o600)

    # --- (e) PII ----------------------------------------------------------
    docs = home / "Documents"
    docs.mkdir()
    pan = docs / "visa 4111 1111 1111 1111 exp 0327 cvv 415.csv"
    pan.write_text("statement for account\n")
    _touch(pan)
    tax = docs / "tax-export.csv"
    tax.write_text(
        "name,email,sin\n"
        "A Person,a.person@example.test,123-45-6789\n"
        "B Person,b.person@example.test,987-65-4321\n"
    )
    _touch(tax)

    # --- (b) Apple Notes --------------------------------------------------
    notes = home / "Library" / "Group Containers" / "group.com.apple.notes"
    notes.mkdir(parents=True)
    conn = sqlite3.connect(str(notes / "NoteStore.sqlite"))
    conn.execute("CREATE TABLE ZICNOTEDATA (Z_PK INTEGER PRIMARY KEY, ZDATA BLOB)")
    conn.execute(
        "CREATE TABLE ZICCLOUDSYNCINGOBJECT (Z_PK INTEGER PRIMARY KEY,"
        " ZNOTEDATA INTEGER, ZTITLE1 TEXT, ZMODIFICATIONDATE1 REAL)"
    )
    body = SEED_PHRASE + "\nrecovery phrase for my hardware wallet"
    conn.execute("INSERT INTO ZICNOTEDATA VALUES (?, ?)",
                 (7, gzip.compress(body.encode())))
    conn.execute("INSERT INTO ZICCLOUDSYNCINGOBJECT VALUES (?, ?, ?, ?)",
                 (1, 7, SEED_PHRASE, CORE_DATA_MODIFIED))
    conn.execute("INSERT INTO ZICNOTEDATA VALUES (?, ?)", (8, b"\x01locked-note"))
    conn.execute("INSERT INTO ZICNOTEDATA VALUES (?, ?)", (9, b"\x01locked-note"))
    conn.commit()
    conn.close()

    # --- (a) Chromium profile: logins, cookies, a wallet extension --------
    prof = (home / "Library" / "Application Support" / "Google" / "Chrome" /
            "Default")
    prof.mkdir(parents=True)
    conn = sqlite3.connect(str(prof / "Login Data"))
    conn.execute(
        "CREATE TABLE logins (origin_url TEXT, username_value TEXT,"
        " password_value BLOB, blacklisted_by_user INTEGER)"
    )
    conn.executemany(
        "INSERT INTO logins VALUES (?,?,?,0)",
        [
            ("https://example-bank.test/login", "someone", b"x" * 40),
            ("https://example-forum.test/login", "someone", b"x" * 40),
        ],
    )
    conn.commit()
    conn.close()
    conn = sqlite3.connect(str(prof / "Cookies"))
    conn.execute("CREATE TABLE cookies (host_key TEXT, name TEXT)")
    conn.executemany(
        "INSERT INTO cookies VALUES (?,?)",
        [("example-bank.test", f"c{i}") for i in range(9)] +
        [("github.com", f"c{i}") for i in range(7)] +
        [("example-forum.test", f"c{i}") for i in range(20)],
    )
    conn.commit()
    conn.close()
    for ext, files in (
        ("nkbihfbeogaeaoehlefnkodbefgpgknn", 3),      # MetaMask
        ("bfnaelmomeimhlpmgjnjophhpkkoljpa", 2),      # Phantom
    ):
        d = prof / "Local Extension Settings" / ext
        d.mkdir(parents=True)
        for i in range(files):
            (d / f"{i:06d}.ldb").write_bytes(b"\x00leveldb")

    # --- Firefox ----------------------------------------------------------
    ff = (home / "Library" / "Application Support" / "Firefox" / "Profiles" /
          "aaaaaaaa.default-release")
    ff.mkdir(parents=True)
    (ff / "logins.json").write_text(json.dumps({"logins": [
        {"hostname": "https://example-bank.test", "encryptedUsername": "REDACTED"},
        {"hostname": "https://example-forum.test", "encryptedUsername": "REDACTED"},
        {"hostname": "https://example-shop.test", "encryptedUsername": "REDACTED"},
    ]}))
    conn = sqlite3.connect(str(ff / "cookies.sqlite"))
    conn.execute("CREATE TABLE moz_cookies (host TEXT)")
    conn.executemany("INSERT INTO moz_cookies VALUES (?)",
                     [("example-forum.test",)] * 14)
    conn.commit()
    conn.close()

    # --- (f) developer credentials ---------------------------------------
    ssh = home / ".ssh"
    ssh.mkdir(mode=0o700)
    for name, passphrase in (("id_ed25519_example", ""),
                             ("id_ed25519_example_locked", "not-a-real-passphrase")):
        subprocess.run(
            ["ssh-keygen", "-t", "ed25519", "-N", passphrase, "-C", "example",
             "-f", str(ssh / name), "-q"],
            check=True, capture_output=True,
        )
    (home / ".npmrc").write_text(
        "//registry.npmjs.org/:_authToken=npm_PLACEHOLDER00000000000000000000\n"
    )
    os.chmod(home / ".npmrc", 0o600)
    gh = home / ".config" / "gh"
    gh.mkdir(parents=True)
    (gh / "hosts.yml").write_text(
        "github.com:\n"
        "    oauth_token: gho_PLACEHOLDER00000000000000000000\n"
        "    user: example-user\n"
        "    git_protocol: ssh\n"
    )
    os.chmod(gh / "hosts.yml", 0o600)
    docker = home / ".docker"
    docker.mkdir()
    (docker / "config.json").write_text(json.dumps(
        {"auths": {"https://index.docker.io/v1/": {"auth": "UExBQ0VIT0xERVI="}},
         "credsStore": "desktop"}, indent=1))
    os.chmod(docker / "config.json", 0o644)
    (home / ".zsh_history").write_text(
        ": 1767225600:0;cd ~/dev\n"
        ": 1767225601:0;ls -la\n"
        ": 1767225602:0;export EXAMPLE_API_KEY=sk-PLACEHOLDER000000000000000000000000\n"
        ": 1767225603:0;git push\n"
    )

    # --- (h) keychain -----------------------------------------------------
    kc = home / "Library" / "Keychains"
    kc.mkdir(parents=True)
    (kc / "login.keychain-db").write_bytes(b"\x00" * 262_144)

    # --- (i) TCC ----------------------------------------------------------
    tcc = home / es.TCC_USER_DB
    tcc.parent.mkdir(parents=True)
    conn = sqlite3.connect(str(tcc))
    conn.execute(
        "CREATE TABLE access (service TEXT NOT NULL, client TEXT NOT NULL,"
        " client_type INTEGER NOT NULL, auth_value INTEGER NOT NULL)"
    )
    conn.executemany("INSERT INTO access VALUES (?,?,?,?)", [
        ("kTCCServiceAccessibility", "com.apple.Terminal", 0, 2),
        ("kTCCServiceScreenCapture", "com.apple.Terminal", 0, 2),
        ("kTCCServiceSystemPolicyAllFiles", "/usr/libexec/sshd-keygen-wrapper", 1, 2),
        ("kTCCServiceAccessibility", "com.example.WindowTool", 0, 2),
        ("kTCCServicePhotos", "com.example.PhotoApp", 0, 2),
        ("kTCCServiceCamera", "com.example.MeetingApp", 0, 2),
        ("kTCCServiceScreenCapture", "com.example.DeniedApp", 0, 0),
    ])
    conn.commit()
    conn.close()


FAKE_COMMANDS = {
    "SecureKeyboardEntry": "0\n",
    "print-disabled": (
        'disabled services = {\n'
        '\t"com.openssh.sshd" => false\n'
        '\t"com.apple.screensharing" => true\n'
        '}\n'
    ),
    "show-keychain-info": 'Keychain "login.keychain-db" no-timeout\n',
    "SPiBridgeDataType": (
        "        Secure Boot: Reduced Security\n"
        "        Allow All Kernel Extensions: Yes\n"
    ),
}


def generate() -> str:
    # A DETERMINISTIC, SHORT temp root. Not mkdtemp(): a random suffix is a
    # high-entropy run, so redact() would (correctly) eat it and every Location
    # line in the sample would read "<redacted>". The name is also kept under
    # 20 characters for the same reason.
    home = Path("/tmp/cfk-sample")
    shutil.rmtree(home, ignore_errors=True)
    home.mkdir(parents=True)
    real_home, real_run, real_sys_tcc = Path.home, es._safe_run, es.TCC_SYSTEM_DB
    try:
        build_home(home)
        Path.home = staticmethod(lambda: home)          # type: ignore[assignment]
        es.TCC_SYSTEM_DB = str(home / "no-system-TCC.db")

        def fake_run(cmd, timeout=8.0):
            joined = " ".join(cmd)
            for key, out in FAKE_COMMANDS.items():
                if key in joined:
                    return out
            return ""

        es._safe_run = fake_run                          # type: ignore[assignment]
        result = es.run_scan(
            home / "dev", do_notes=True, do_browser=True,
            do_dev_creds=True, do_tcc=True,
        )
        markdown = es.render_markdown(result, home / "dev")
    finally:
        Path.home = real_home                            # type: ignore[assignment]
        es._safe_run = real_run                          # type: ignore[assignment]
        es.TCC_SYSTEM_DB = real_sys_tcc
        shutil.rmtree(home, ignore_errors=True)

    # Normalise the two non-deterministic things: the temp home and "now".
    markdown = markdown.replace(str(home), "/Users/PLACEHOLDER")
    markdown = re.sub(
        r"_Generated \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC",
        "_Generated 2026-01-01 00:00 UTC", markdown,
    )
    # Drop in the provenance banner after the invariant blockquote.
    marker = "not an extractor.\n"
    markdown = markdown.replace(marker, marker + BANNER + "\n", 1)
    return markdown


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if sample-report.md is out of date")
    args = ap.parse_args()
    md = generate()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current.strip() != md.strip():
            print("sample-report.md is out of date; run tests/make-sample-report.py",
                  file=sys.stderr)
            return 1
        print("sample-report.md is current")
        return 0
    OUT.write_text(md)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
